### ISSUE TITLE
Rate limited by OpenAI

### ISSUE THREAD

**Issue by ninofiliu** [mmaorc/codezen#2]
This extension is promising and I'm not really raising an issue about it per se but when I tried to run it on my company's webapp, it exploded OpenAI rate limitations: max 10K tokens, but requested 4M tokens. The src folder of my repo has 500K lines, 1M words and 22M characters. Luckily it just aborted the request to OpenAI but if I didn't have a limit set it could have charged me a lot... Maybe a warning would be nice? With an eyeball'd price estimation directly from the command line, that would be nice innit?:)

Also I don't know if CodeZen ignores files it should ignore (like node_modules content), but it could probably be a good optimization.

```
nino@nino~/tc/tucanamapchart-drill$ python -m codezen "hello"
WARNING:langchain.chat_models.openai:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised RateLimitError: Request too large for gpt-4 in organization org-65KOwu1Jpk9B135J7b4ViPyO on tokens per min (TPM): Limit 10000, Requested 4182863. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing..
WARNING:langchain.chat_models.openai:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 2.0 seconds as it raised RateLimitError: Request too large for gpt-4 in organization org-65KOwu1Jpk9B135J7b4ViPyO on tokens per min (TPM): Limit 10000, Requested 4182863. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing..
```

**Comment by mmaorc** [comment]
Hi, thanks for the suggestion! 

This code is a super hacky and only works for small codebases since it sends the entire codebase for each LLM request.
This project is quite old and I'm not maintaining it anymore. I think there should be much better and more complete solutions for this problem these days.

Here are some suggestions that I didn't try personally but might work for you.

Paid:
* Cody https://github.com/sourcegraph/cody
* Github copilot chat

Open source:
* https://github.com/fjrdomingues/autopilot
* https://github.com/smol-ai/developer/
* https://github.com/askrella/git-gpt
